---
- name: Main playbook for cleaning papers in SQLite database
  hosts: localhost
  vars:
    database: "{{ lookup('env', 'PWD') }}/papers.db"
    limit: 1
  tasks:
    - name: "Fetch papers from SQLite database, limit: {{ limit }}"
      lwe_sqlite_query:
        db: "{{ database }}"
        query: "SELECT id, paper_url FROM papers WHERE processing_status = 'ready_to_clean' ORDER BY id LIMIT ?"
        query_params:
          - "{{ limit }}"
      register: paper_results

    - name: Process each paper
      ansible.builtin.include_tasks: raspberry-paper-cleaner-clean.yaml
      loop: "{{ paper_results.data }}"
      loop_control:
        loop_var: paper
      vars:
        current_url: "{{ paper.paper_url }}"
        paper_id: "{{ paper.id }}"
