---
- name: Main playbook for grading papers in SQLite database for CoT using a rubric
  hosts: localhost
  vars:
    grading_preset: "claude-sonnet"
    # grading_preset: "llama-3.2-90b"
    template: "raspberry-paper-grading-rubric.md"
    database: "{{ lookup('env', 'PWD') }}/papers.db"
    limit: 1
    inference_results_directory: "{{ lookup('env', 'PWD') }}/results/inference"
    processing_script: "{{ lookup('env', 'PWD') }}/scripts/raspberry-paper-grading.py"
    # Use system independent temp dir
    tmp_pdf_path: "/tmp/raspberry-tmp-pdf.pdf"
  tasks:

    - name: "Ensure inference results directory exists: {{ inference_results_directory }}"
      ansible.builtin.file:
        path: "{{ inference_results_directory }}"
        state: directory
        mode: '0755'

    - name: "Fetch papers from SQLite database, limit: {{ limit }}"
      lwe_sqlite_query:
        db: "{{ database }}"
        query: "SELECT id, paper_url FROM papers WHERE processing_status = 'ready_to_grade' ORDER BY id LIMIT ?"
        query_params:
          - "{{ limit }}"
      register: paper_results

    - name: Process each paper
      ansible.builtin.include_tasks: raspberry-paper-rubric-grader-grade.yaml
      loop: "{{ paper_results.data }}"
      loop_control:
        loop_var: paper
      vars:
        current_url: "{{ paper.paper_url }}"
        paper_id: "{{ paper.id }}"
